num1 = int(input("enetr num1 "))
num2 = int(input("enetr num2  "))
num3 = int(input("enetr num3 " ))
num4 = int(input("enetr num4 " ))
num5 = int(input("enetr num5 " ))
num6 = int(input("enetr num6 " ))
num7 = int(input("enetr num7 " ))
num8 = int(input("enetr num8 " ))
s = ( num1,num2,num3,num4,num5,num6,num7,num8)
print(s)
